global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmniindiadistro
  name: ndhm-react
  tag: latest

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}

