name: Build and Publish
on:
  push:
    branches: [master,BAH-1439]
    paths-ignore:
      - "**.md"

env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Download ndhm-react.zip
        run: zip -r ndhm-react.zip build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: package/docker/Dockerfile
          push: true
          tags: bahmni/bahmni-web:${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmni/bahmni-web:0.94-ndhm-1
